export const GET_GOODS = 'GET_GOODS',
  GET_LOADING_FALSE = 'GET_LOADING_FALSE',
  ADD_ORDER = 'ADD_ORDER',
  CHANGE_ORDER = 'CHANGE_ORDER',
  VISIBLE_CART = 'VISIBLE_CART',
  DELETE_ORDER = 'DELETE_ORDER',
  INCREASE_QUANTITY = 'INCREASE_QUANTITY',
  DECREASE_QUANTITY = 'DECREASE_QUANTITY'